---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: yes
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      pause:
        seconds : 180

    - name: Updates apt cache
      apt:
      update_cache: yes

    - name: "install python for Ansible."
      apt:
        name: python
        state: present
        update_cache: true

  roles:
    - configure-server