- name: "Install NodeJs"
  become: true
  shell: |
    apt -y upgrade
    apt install -y nodejs
    apt install -y npm

- name: "Install pm2"
  become: true
  shell: |
    sudo npm install pm2 -g

- name: "Copy backend to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "Install NodeJs dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 