- name: Install unzip
  become: true
  apt:
    name: unzip
    update_cache: yes

- name: "Creates new directory for backend"
  file:
    path: ~/app
    state: directory

- name: "Copy build archive"
  copy:
    src: build.zip
    dest: "~/app/build.zip"

- name: "Unzip build archive"
  shell: |
    cd ~/app
    unzip -o build.zip
    
- name: "Install dependencies"
  shell: |
    cd ~/app
    npm install

- name: "Executing node"
  shell: |
    export
    cd ~/app
    pm2 start main.js
  register: execute_node
  environment:
    ENVIRONMENT: "production"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"