- name: "Creates new directory for backend"
  file:
    path: ~/app
    state: directory

- name: "Copy build archive"
  copy:
    src: build.zip
    dest: "~/app/build.zip"

- name: "Unzip build archive"
  shell: |
    cd ~/app
    unzip -o build.zip
    
- name: "Install dependencies"
  shell: |
    cd ~/app
    npm install

- name: "Executing node"
  shell: |
    export
    cd ~/app
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"